rm(list=ls())
mydata = read.csv("population.csv", header = FALSE)
library(tidyverse)
glimpse(mydata$v4)
hist(as.numeric(unlist(mydata[4])))
boxplot(as.numeric(unlist(mydata[4])))
iqr <- IQR(as.numeric(unlist(mydata[4])))
q<-quantile(as.numeric(unlist(mydata[4])))
mean(as.numeric(unlist(mydata[4])))
length(boxplot.stats(as.numeric(unlist(mydata[4])))$out)
length(as.numeric(unlist(mydata[4])))
upper  = min(max(as.numeric(unlist(mydata[4]))), q[4] + 1.5 * iqr)
lower  = max(min(as.numeric(unlist(mydata[4]))), q[2] - 1.5 * iqr)


rm(list=ls())
mydata = read.csv("covid_new.csv", header = FALSE)
library(tidyverse)
glimpse(mydata$v4)
hist(as.numeric(unlist(mydata[4])))
boxplot(as.numeric(unlist(mydata[4])))
iqr <- IQR(as.numeric(unlist(mydata[4])))
q<-quantile(as.numeric(unlist(mydata[4])))
mean(as.numeric(unlist(mydata[4])))
length(boxplot.stats(as.numeric(unlist(mydata[4])))$out)
length(as.numeric(unlist(mydata[4])))
upper  = min(max(as.numeric(unlist(mydata[4]))), q[4] + 1.5 * iqr)
lower  = max(min(as.numeric(unlist(mydata[4]))), q[2] - 1.5 * iqr)



rm(list=ls())
mydata = read.csv("bachelorPercentage.csv", header = FALSE)
library(tidyverse)
glimpse(mydata$v4)
hist(as.numeric(unlist(mydata[4])))
boxplot(as.numeric(unlist(mydata[4])))
iqr <- IQR(as.numeric(unlist(mydata[4])))
q<-quantile(as.numeric(unlist(mydata[4])))
mean(as.numeric(unlist(mydata[4])))
length(boxplot.stats(as.numeric(unlist(mydata[4])))$out)
length(as.numeric(unlist(mydata[4])))
upper  = min(max(as.numeric(unlist(mydata[4]))), q[4] + 1.5 * iqr)
lower  = max(min(as.numeric(unlist(mydata[4]))), q[2] - 1.5 * iqr)


rm(list=ls())
mydata = read.csv("median_income.csv", header = FALSE)
library(tidyverse)
glimpse(mydata$v4)
hist(as.numeric(unlist(mydata[4])))
boxplot(as.numeric(unlist(mydata[4])))
iqr <- IQR(as.numeric(unlist(mydata[4])))
q<-quantile(as.numeric(unlist(mydata[4])))
mean(as.numeric(unlist(mydata[4])))
length(boxplot.stats(as.numeric(unlist(mydata[4])))$out)
length(as.numeric(unlist(mydata[4])))
upper  = min(max(as.numeric(unlist(mydata[4]))), q[4] + 1.5 * iqr)
lower  = max(min(as.numeric(unlist(mydata[4]))), q[2] - 1.5 * iqr)


rm(list=ls())
mydata = read.csv("below_poverty_percent.csv", header = FALSE)
library(tidyverse)
glimpse(mydata$v4)
hist(as.numeric(unlist(mydata[4])))
boxplot(as.numeric(unlist(mydata[4])))
iqr <- IQR(as.numeric(unlist(mydata[4])))
q<-quantile(as.numeric(unlist(mydata[4])))
mean(as.numeric(unlist(mydata[4])))
length(boxplot.stats(as.numeric(unlist(mydata[4])))$out)
length(as.numeric(unlist(mydata[4])))
upper  = min(max(as.numeric(unlist(mydata[4]))), q[4] + 1.5 * iqr)
lower  = max(min(as.numeric(unlist(mydata[4]))), q[2] - 1.5 * iqr)


rm(list=ls())
mydata = read.csv("four_plus_family_percent.csv", header = FALSE)
library(tidyverse)
glimpse(mydata$v4)
hist(as.numeric(unlist(mydata[4])))
boxplot(as.numeric(unlist(mydata[4])))
iqr <- IQR(as.numeric(unlist(mydata[4])))
q<-quantile(as.numeric(unlist(mydata[4])))
mean(as.numeric(unlist(mydata[4])))
length(boxplot.stats(as.numeric(unlist(mydata[4])))$out)
length(as.numeric(unlist(mydata[4])))
upper  = min(max(as.numeric(unlist(mydata[4]))), q[4] + 1.5 * iqr)
lower  = max(min(as.numeric(unlist(mydata[4]))), q[2] - 1.5 * iqr)


rm(list=ls())
mydata = read.csv("no_car_percent.csv", header = FALSE)
library(tidyverse)
glimpse(mydata$v4)
hist(as.numeric(unlist(mydata[4])))
boxplot(as.numeric(unlist(mydata[4])))
iqr <- IQR(as.numeric(unlist(mydata[4])))
q<-quantile(as.numeric(unlist(mydata[4])))
mean(as.numeric(unlist(mydata[4])))
length(boxplot.stats(as.numeric(unlist(mydata[4])))$out)
length(as.numeric(unlist(mydata[4])))
upper  = min(max(as.numeric(unlist(mydata[4]))), q[4] + 1.5 * iqr)
lower  = max(min(as.numeric(unlist(mydata[4]))), q[2] - 1.5 * iqr)


rm(list=ls())
mydata = read.csv("unemployment_percent.csv", header = FALSE)
library(tidyverse)
glimpse(mydata$v4)
hist(as.numeric(unlist(mydata[4])))
boxplot(as.numeric(unlist(mydata[4])))
iqr <- IQR(as.numeric(unlist(mydata[4])))
q<-quantile(as.numeric(unlist(mydata[4])))
mean(as.numeric(unlist(mydata[4])))
length(boxplot.stats(as.numeric(unlist(mydata[4])))$out)
length(as.numeric(unlist(mydata[4])))
upper  = min(max(as.numeric(unlist(mydata[4]))), q[4] + 1.5 * iqr)
lower  = max(min(as.numeric(unlist(mydata[4]))), q[2] - 1.5 * iqr)

